export const S3_ACCESS_KEY_ID = process.env.NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID
export const S3_SECRET_ACCESS_KEY = process.env.NEXT_PUBLIC_AWS_S3_SECRET_ACCESS_KEY
export const S3_REGION = process.env.NEXT_PUBLIC_AWS_S3_REGION
export const S3_BUCKET_NAME = process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME